import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Star Connect | Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex items-center justify-center absolute top-[22%] left-[40%]">{children}</div>
  );
}
